language: node_js
node_js:
  - lts/carbon
  - node
git:
  depth: 5
before_script:
  # https://github.com/lerna/lerna/issues/1457#issuecomment-399678173
  - yarn lerna exec yarn install
  - yarn lerna link --force-local
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git fetch --tags
deploy:
  provider: script
  script: yarn publish-ci
  skip_cleanup: true
  on:
    branch: master
