name: CI

on: [push, pull_request]

jobs:
  default:
    name: Build and Test on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node:
          - 12
          - 14
          - 16
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: yarn --frozen-lockfile
        env:
          CI: 'true'
      - name: Test
        run: yarn test
